// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"
	"github.com/summer-gonner/traffica/sys/internal/logic/dictitemservice"
	"github.com/summer-gonner/traffica/sys/internal/svc"
	sysclient2 "github.com/summer-gonner/traffica/sys/sysclient"
)

type DictItemServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient2.UnimplementedDictItemServiceServer
}

func NewDictItemServiceServer(svcCtx *svc.ServiceContext) *DictItemServiceServer {
	return &DictItemServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加字典数据表
func (s *DictItemServiceServer) AddDictItem(ctx context.Context, in *sysclient2.AddDictItemReq) (*sysclient2.AddDictItemResp, error) {
	l := dictitemservicelogic.NewAddDictItemLogic(ctx, s.svcCtx)
	return l.AddDictItem(in)
}

// 删除字典数据表
func (s *DictItemServiceServer) DeleteDictItem(ctx context.Context, in *sysclient2.DeleteDictItemReq) (*sysclient2.DeleteDictItemResp, error) {
	l := dictitemservicelogic.NewDeleteDictItemLogic(ctx, s.svcCtx)
	return l.DeleteDictItem(in)
}

// 更新字典数据表
func (s *DictItemServiceServer) UpdateDictItem(ctx context.Context, in *sysclient2.UpdateDictItemReq) (*sysclient2.UpdateDictItemResp, error) {
	l := dictitemservicelogic.NewUpdateDictItemLogic(ctx, s.svcCtx)
	return l.UpdateDictItem(in)
}

// 更新字典数据表状态
func (s *DictItemServiceServer) UpdateDictItemStatus(ctx context.Context, in *sysclient2.UpdateDictItemStatusReq) (*sysclient2.UpdateDictItemStatusResp, error) {
	l := dictitemservicelogic.NewUpdateDictItemStatusLogic(ctx, s.svcCtx)
	return l.UpdateDictItemStatus(in)
}

// 查询字典数据表详情
func (s *DictItemServiceServer) QueryDictItemDetail(ctx context.Context, in *sysclient2.QueryDictItemDetailReq) (*sysclient2.QueryDictItemDetailResp, error) {
	l := dictitemservicelogic.NewQueryDictItemDetailLogic(ctx, s.svcCtx)
	return l.QueryDictItemDetail(in)
}

// 查询字典数据表列表
func (s *DictItemServiceServer) QueryDictItemList(ctx context.Context, in *sysclient2.QueryDictItemListReq) (*sysclient2.QueryDictItemListResp, error) {
	l := dictitemservicelogic.NewQueryDictItemListLogic(ctx, s.svcCtx)
	return l.QueryDictItemList(in)
}
