apiVersion: v1
kind: ServiceAccount
metadata:
  name: koobe
  namespace: zero-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: koobe-endpoints
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: koobe-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: koobe-endpoints
subjects:
  - kind: ServiceAccount
    name: koobe
    namespace: zero-admin