// Code generated by goctl. DO NOT EDIT.
package types

type AddDeptReq struct {
	DeptName   string  `json:"deptName"`        //部门名称
	DeptSort   int32   `json:"deptSort"`        //部门排序
	DeptStatus int32   `json:"deptStatus"`      //部门状态
	Email      string  `json:"email"`           //邮箱
	Leader     string  `json:"leader"`          //负责人
	ParentId   int64   `json:"parentId"`        //上级机构ID，一级机构为0
	ParentIds  []int64 `json:"parentIds"`       //上级机构IDs，一级机构为0
	Phone      string  `json:"phone"`           //电话号码
	Remark     string  `json:"remark,optional"` //备注信息
}

type AddDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddDictItemReq struct {
	DictLabel  string `json:"dictLabel"`       //字典标签
	DictSort   int32  `json:"dictSort"`        //排序
	DictStatus int32  `json:"dictStatus"`      //字典状态
	DictType   string `json:"dictType"`        //字典类型
	DictValue  string `json:"dictValue"`       //字典键值
	IsDefault  int32  `json:"isDefault"`       //是否默认  0：否  1：是
	Remark     string `json:"remark,optional"` //备注信息
}

type AddDictItemResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddDictTypeReq struct {
	DictName   string `json:"dictName"`        //字典名称
	DictStatus int32  `json:"dictStatus"`      //字典状态
	DictType   string `json:"dictType"`        //字典类型
	IsSystem   int32  `json:"isSystem"`        //是否系统预留  0：否  1：是
	Remark     string `json:"remark,optional"` //备注信息
}

type AddDictTypeResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddMenuReq struct {
	BackgroundUrl string `json:"backgroundUrl,optional"` //接口地址
	MenuIcon      string `json:"menuIcon,optional"`      //菜单图标
	MenuName      string `json:"menuName"`               //菜单名称
	MenuPath      string `json:"menuPath,optional"`      //前端路由
	MenuPerms     string `json:"menuPerms,optional"`     //权限标识
	MenuSort      int32  `json:"menuSort,optional"`      //菜单排序
	MenuStatus    int32  `json:"menuStatus,optional"`    //菜单状态
	MenuType      int32  `json:"menuType,optional"`      //类型 0：目录,1：菜单,2：按钮,3：外链
	ParentId      int64  `json:"parentId,optional"`      //父菜单ID，一级菜单为0
	Remark        string `json:"remark,optional"`        //备注信息
	VueComponent  string `json:"vueComponent,optional"`  //vue的页面
	VueIcon       string `json:"vueIcon,optional"`       //vue的图标
	VuePath       string `json:"vuePath,optional"`       //vue系统的path
	VueRedirect   string `json:"vueRedirect,optional"`   //vue的路由重定向
	IsVisible     int32  `json:"isVisible,default=1"`    //是否可见  0：否  1：是
}

type AddMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddPostReq struct {
	PostCode   string `json:"postCode"`        //岗位编码
	PostName   string `json:"postName"`        //岗位名称
	PostSort   int32  `json:"postSort"`        //岗位排序
	PostStatus int32  `json:"postStatus"`      //岗位状态
	Remark     string `json:"remark,optional"` //备注信息
}

type AddPostResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddRoleReq struct {
	DataScope  int32  `json:"dataScope,default=0"` //数据权限
	IsAdmin    int32  `json:"isAdmin,default=0"`   //是否超级管理员
	Remark     string `json:"remark,optional"`     //备注
	RoleKey    string `json:"roleKey"`             //权限字符
	RoleName   string `json:"roleName"`            //角色名称
	RoleSort   int32  `json:"roleSort"`            //角色排序
	RoleStatus int32  `json:"roleStatus"`          //角色状态
}

type AddRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddUserReq struct {
	Avatar     string  `json:"avatar,optional"`  //头像
	DeptId     int64   `json:"deptId,optional"`  //部门id
	PostIds    []int64 `json:"postIds,optional"` //部门id
	Email      string  `json:"email,optional"`   //邮箱
	Mobile     string  `json:"mobile"`           //手机号
	NickName   string  `json:"nickName"`         //昵称
	Remark     string  `json:"remark,optional"`  //备注信息
	UserName   string  `json:"userName"`         //用户名
	UserStatus int32   `json:"userStatus"`       //帐号状态（0正常 1停用）
}

type AddUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type CancelAuthorizationReq struct {
	RoleId  int64   `json:"roleId"`
	UserIds []int64 `json:"userIds"`
	IsExist int64   `json:"isExist"` //0：取消授权，1：确认授权
}

type CancelAuthorizationResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteDeptReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteDictItemReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteDictItemResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteDictTypeReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteDictTypeResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteLoginLogReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteLoginLogResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteMenuReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteOperateLogReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteOperateLogResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeletePostReq struct {
	Ids []int64 `form:"ids"`
}

type DeletePostResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteRoleReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteUserReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeptList struct {
	Id       int64  `json:"id"`
	DeptKey  string `json:"key"`
	Value    string `json:"value"`
	Title    string `json:"title"`
	ParentId int64  `json:"parentId"`
}

type ListMenuTree struct {
	Id       int64  `json:"id"`       // 编号
	Path     string `json:"path"`     // 菜单路径
	Name     string `json:"name"`     // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID，一级菜单为0
	Icon     string `json:"icon"`     // 菜单图标
}

type ListMenuTreeVue struct {
	Id           int64        `json:"id"`
	ParentId     int64        `json:"parentId"`
	Title        string       `json:"title"`
	Path         string       `json:"path"`
	Name         string       `json:"name"`
	Icon         string       `json:"icon"`
	VueRedirect  string       `json:"redirect"`
	VueComponent string       `json:"component"`
	Meta         MenuTreeMeta `json:"meta"`
}

type LoginData struct {
	AccessToken string `json:"token"`
}

type LoginReq struct {
	Account  string `json:"account"` //手机号或者用户名
	Password string `json:"password"`
}

type LoginResp struct {
	Code    string    `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data"`
}

type MenuTreeListData struct {
	Key      string `json:"key"`      // 菜单名称
	Title    string `json:"title"`    // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID，一级菜单为0
	Id       int64  `json:"id"`       // 父菜单ID，一级菜单为0
	Label    string `json:"label"`    // 父菜单ID，一级菜单为0
}

type MenuTreeMeta struct {
	Title string `json:"title"`
	Icon  string `json:"icon"`
}

type PostList struct {
	Id       int64  `json:"id"`
	PostName string `json:"postName"`
}

type QueryDeptAndPostListData struct {
	DeptList []*DeptList `json:"deptList"`
	PostList []*PostList `json:"postList"`
}

type QueryDeptAndPostListReq struct {
	Current  int64 `form:"current,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type QueryDeptAndPostListResp struct {
	Code    string                   `json:"code"`
	Message string                   `json:"message"`
	Data    QueryDeptAndPostListData `json:"data"`
}

type QueryDeptDetailData struct {
	CreateBy   string  `json:"createBy"`   //创建者
	CreateTime string  `json:"createTime"` //创建时间
	DeptName   string  `json:"deptName"`   //部门名称
	DeptSort   int32   `json:"deptSort"`   //部门排序
	DeptStatus int32   `json:"deptStatus"` //部门状态
	Email      string  `json:"email"`      //邮箱
	Id         int64   `json:"id"`         //编号
	Leader     string  `json:"leader"`     //负责人
	ParentId   int64   `json:"parentId"`   //上级机构ID，一级机构为0
	ParentIds  []int64 `json:"parentIds"`  //上级机构IDs，一级机构为0
	Phone      string  `json:"phone"`      //电话号码
	Remark     string  `json:"remark"`     //备注信息
	UpdateBy   string  `json:"updateBy"`   //更新者
	UpdateTime string  `json:"updateTime"` //更新时间
}

type QueryDeptDetailReq struct {
	Id int64 `form:"id"`
}

type QueryDeptDetailResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    QueryDeptDetailData `json:"data"`
}

type QueryDeptListData struct {
	CreateBy   string  `json:"createBy"`   //创建者
	CreateTime string  `json:"createTime"` //创建时间
	DeptName   string  `json:"deptName"`   //部门名称
	DeptSort   int32   `json:"deptSort"`   //部门排序
	DeptStatus int32   `json:"deptStatus"` //部门状态
	Email      string  `json:"email"`      //邮箱
	Id         int64   `json:"id"`         //编号
	Leader     string  `json:"leader"`     //负责人
	ParentId   int64   `json:"parentId"`   //上级机构ID，一级机构为0
	ParentIds  []int64 `json:"parentIds"`  //上级机构IDs，一级机构为0
	Phone      string  `json:"phone"`      //电话号码
	Remark     string  `json:"remark"`     //备注信息
	UpdateBy   string  `json:"updateBy"`   //更新者
	UpdateTime string  `json:"updateTime"` //更新时间
}

type QueryDeptListReq struct {
}

type QueryDeptListResp struct {
	Code     string               `json:"code"`
	Message  string               `json:"message"`
	Current  int64                `json:"current,default=1"`
	Data     []*QueryDeptListData `json:"data"`
	PageSize int64                `json:"pageSize,default=20"`
	Success  bool                 `json:"success"`
	Total    int64                `json:"total"`
}

type QueryDictItemDetailData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DictLabel  string `json:"dictLabel"`  //字典标签
	DictSort   int32  `json:"dictSort"`   //排序
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	DictValue  string `json:"dictValue"`  //字典键值
	Id         int64  `json:"id"`         //编号
	IsDefault  int32  `json:"isDefault"`  //是否默认  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type QueryDictItemDetailReq struct {
	Id int64 `form:"id"`
}

type QueryDictItemDetailResp struct {
	Code    string                  `json:"code"`
	Message string                  `json:"message"`
	Data    QueryDictItemDetailData `json:"data"`
}

type QueryDictItemListData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DictLabel  string `json:"dictLabel"`  //字典标签
	DictSort   int32  `json:"dictSort"`   //排序
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	DictValue  string `json:"dictValue"`  //字典键值
	Id         int64  `json:"id"`         //编号
	IsDefault  int32  `json:"isDefault"`  //是否默认  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type QueryDictItemListReq struct {
	Current    int64  `form:"current,default=1"`     //第几页
	PageSize   int64  `form:"pageSize,default=20"`   //每页的数量
	DictLabel  string `form:"dictLabel,optional"`    //字典标签
	DictStatus int32  `form:"dictStatus,,default=2"` //字典状态
	DictType   string `form:"dictType,optional"`     //字典类型
}

type QueryDictItemListResp struct {
	Code     string                   `json:"code"`
	Message  string                   `json:"message"`
	Current  int64                    `json:"current,default=1"`
	Data     []*QueryDictItemListData `json:"data"`
	PageSize int64                    `json:"pageSize,default=20"`
	Success  bool                     `json:"success"`
	Total    int64                    `json:"total"`
}

type QueryDictTypeDetailData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DictName   string `json:"dictName"`   //字典名称
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	Id         int64  `json:"id"`         //编号
	IsSystem   int32  `json:"isSystem"`   //是否系统预留  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type QueryDictTypeDetailReq struct {
	Id int64 `form:"id"`
}

type QueryDictTypeDetailResp struct {
	Code    string                  `json:"code"`
	Message string                  `json:"message"`
	Data    QueryDictTypeDetailData `json:"data"`
}

type QueryDictTypeListData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DictName   string `json:"dictName"`   //字典名称
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	Id         int64  `json:"id"`         //编号
	IsSystem   int32  `json:"isSystem"`   //是否系统预留  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type QueryDictTypeListReq struct {
	Current    int64  `form:"current,default=1"`    //第几页
	PageSize   int64  `form:"pageSize,default=20"`  //每页的数量
	DictName   string `form:"dictName,optional"`    //字典名称
	DictStatus int32  `form:"dictStatus,default=2"` //字典状态
	DictType   string `form:"dictType,optional"`    //字典类型
	IsSystem   int32  `form:"isSystem,default=2"`   //是否系统预留  0：否  1：是
}

type QueryDictTypeListResp struct {
	Code     string                   `json:"code"`
	Message  string                   `json:"message"`
	Current  int64                    `json:"current,default=1"`
	Data     []*QueryDictTypeListData `json:"data"`
	PageSize int64                    `json:"pageSize,default=20"`
	Success  bool                     `json:"success"`
	Total    int64                    `json:"total"`
}

type QueryLoginLogDetailData struct {
	Browser     string `json:"browser"`     //浏览器
	Id          int64  `json:"id"`          //编号
	IpAddress   string `json:"ipAddress"`   //IP地址
	LoginStatus string `json:"loginStatus"` //登录状态
	LoginTime   string `json:"loginTime"`   //登录时间
	Os          string `json:"os"`          //操作信息
	UserName    string `json:"userName"`    //用户名
	ErrorMsg    string `json:"errorMsg"`    //操作信息
}

type QueryLoginLogDetailReq struct {
	Id int64 `form:"id"`
}

type QueryLoginLogDetailResp struct {
	Code    string                  `json:"code"`
	Message string                  `json:"message"`
	Data    QueryLoginLogDetailData `json:"data"`
}

type QueryLoginLogListData struct {
	Browser     string `json:"browser"`     //浏览器
	Id          int64  `json:"id"`          //编号
	IpAddress   string `json:"ipAddress"`   //IP地址
	LoginStatus string `json:"loginStatus"` //登录状态
	LoginTime   string `json:"loginTime"`   //登录时间
	Os          string `json:"os"`          //操作信息
	UserName    string `json:"userName"`    //用户名
	ErrorMsg    string `json:"errorMsg"`    //操作信息
}

type QueryLoginLogListReq struct {
	Current     int64  `form:"current,default=1"`    //第几页
	PageSize    int64  `form:"pageSize,default=20"`  //每页的数量
	Browser     string `form:"browser,optional"`     //浏览器
	IpAddress   string `form:"ipAddress,optional"`   //IP地址
	LoginStatus string `form:"loginStatus,optional"` //登录状态
	Os          string `form:"os,optional"`          //操作信息
	UserName    string `form:"userName,optional"`    //用户名
}

type QueryLoginLogListResp struct {
	Code     string                   `json:"code"`
	Message  string                   `json:"message"`
	Current  int64                    `json:"current,default=1"`
	Data     []*QueryLoginLogListData `json:"data"`
	PageSize int64                    `json:"pageSize,default=20"`
	Success  bool                     `json:"success"`
	Total    int64                    `json:"total"`
}

type QueryMenuDetailData struct {
	BackgroundUrl string `json:"backgroundUrl"`       //接口地址
	CreateBy      string `json:"createBy"`            //创建者
	CreateTime    string `json:"createTime"`          //创建时间
	Id            int64  `json:"id"`                  //编号
	MenuIcon      string `json:"menuIcon"`            //菜单图标
	MenuName      string `json:"menuName"`            //菜单名称
	MenuPath      string `json:"menuPath"`            //前端路由
	MenuPerms     string `json:"menuPerms"`           //权限标识
	MenuSort      int32  `json:"menuSort"`            //菜单排序
	MenuStatus    int32  `json:"menuStatus"`          //菜单状态
	MenuType      int32  `json:"menuType"`            //类型 0：目录,1：菜单,2：按钮,3：外链
	ParentId      int64  `json:"parentId"`            //父菜单ID，一级菜单为0
	Remark        string `json:"remark"`              //备注信息
	UpdateBy      string `json:"updateBy"`            //更新者
	UpdateTime    string `json:"updateTime"`          //更新时间
	VueComponent  string `json:"vueComponent"`        //vue的页面
	VueIcon       string `json:"vueIcon"`             //vue的图标
	VuePath       string `json:"vuePath"`             //vue系统的path
	VueRedirect   string `json:"vueRedirect"`         //vue的路由重定向
	IsVisible     int32  `json:"isVisible,default=1"` //是否可见  0：否  1：是
}

type QueryMenuDetailReq struct {
	Id int64 `form:"id"`
}

type QueryMenuDetailResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    QueryMenuDetailData `json:"data"`
}

type QueryMenuListData struct {
	BackgroundUrl string `json:"backgroundUrl"`       //接口地址
	CreateBy      string `json:"createBy"`            //创建者
	CreateTime    string `json:"createTime"`          //创建时间
	Id            int64  `json:"id"`                  //编号
	MenuIcon      string `json:"menuIcon"`            //菜单图标
	MenuName      string `json:"menuName"`            //菜单名称
	MenuPath      string `json:"menuPath"`            //前端路由
	MenuPerms     string `json:"menuPerms"`           //权限标识
	MenuSort      int32  `json:"menuSort"`            //菜单排序
	MenuStatus    int32  `json:"menuStatus"`          //菜单状态
	MenuType      int32  `json:"menuType"`            //类型 0：目录,1：菜单,2：按钮,3：外链
	ParentId      int64  `json:"parentId"`            //父菜单ID，一级菜单为0
	Remark        string `json:"remark"`              //备注信息
	UpdateBy      string `json:"updateBy"`            //更新者
	UpdateTime    string `json:"updateTime"`          //更新时间
	VueComponent  string `json:"vueComponent"`        //vue的页面
	VueIcon       string `json:"vueIcon"`             //vue的图标
	VuePath       string `json:"vuePath"`             //vue系统的path
	VueRedirect   string `json:"vueRedirect"`         //vue的路由重定向
	IsVisible     int32  `json:"isVisible,default=1"` //是否可见  0：否  1：是
}

type QueryMenuListReq struct {
}

type QueryMenuListResp struct {
	Code     string               `json:"code"`
	Message  string               `json:"message"`
	Current  int64                `json:"current,default=1"`
	Data     []*QueryMenuListData `json:"data"`
	PageSize int64                `json:"pageSize,default=20"`
	Success  bool                 `json:"success"`
	Total    int64                `json:"total"`
}

type QueryOperateLogDetailData struct {
	DeptName          string `json:"deptName"`          //部门名称
	Id                int64  `json:"id"`                //编号
	OperationIp       string `json:"operationIp"`       //操作地址
	OperationName     string `json:"operationName"`     //操作人员
	OperationParams   string `json:"operationParams"`   //请求参数
	OperationResponse string `json:"operationResponse"` //响应参数
	OperationStatus   int32  `json:"operationStatus"`   //操作状态
	OperationTime     string `json:"operationTime"`     //操作时间
	OperationType     string `json:"operationType"`     //操作类型
	OperationUrl      string `json:"operationUrl"`      //操作方法
	RequestMethod     string `json:"requestMethod"`     //请求方式
	Title             string `json:"title"`             //系统模块
	UseTime           int64  `json:"useTime"`           //执行时长(毫秒)
	Browser           string `json:"browser"`           //浏览器
	Os                string `json:"os"`                //操作信息
}

type QueryOperateLogDetailReq struct {
	Id int64 `form:"id"`
}

type QueryOperateLogDetailResp struct {
	Code    string                    `json:"code"`
	Message string                    `json:"message"`
	Data    QueryOperateLogDetailData `json:"data"`
}

type QueryOperateLogListData struct {
	DeptName          string `json:"deptName"`          //部门名称
	Id                int64  `json:"id"`                //编号
	OperationIp       string `json:"operationIp"`       //操作地址
	OperationName     string `json:"operationName"`     //操作人员
	OperationParams   string `json:"operationParams"`   //请求参数
	OperationResponse string `json:"operationResponse"` //响应参数
	OperationStatus   int32  `json:"operationStatus"`   //操作状态
	OperationTime     string `json:"operationTime"`     //操作时间
	OperationType     string `json:"operationType"`     //操作类型
	OperationUrl      string `json:"operationUrl"`      //操作方法
	RequestMethod     string `json:"requestMethod"`     //请求方式
	Title             string `json:"title"`             //系统模块
	UseTime           int64  `json:"useTime"`           //执行时长(毫秒)
	Browser           string `json:"browser"`           //浏览器
	Os                string `json:"os"`                //操作信息
}

type QueryOperateLogListReq struct {
	Current         int64  `form:"current,default=1"`        //第几页
	PageSize        int64  `form:"pageSize,default=20"`      //每页的数量
	DeptName        string `form:"deptName,optional"`        //部门名称
	OperationIp     string `form:"operationIp,optional"`     //操作地址
	OperationName   string `form:"operationName,optional"`   //操作人员
	OperationStatus int32  `form:"operationStatus,optional"` //操作状态
	OperationType   string `form:"operationType,optional"`   //操作类型
	OperationUrl    string `form:"operationUrl,optional"`    //操作方法
	Title           string `form:"title,optional"`           //系统模块
	Browser         string `json:"browser,optional"`         //浏览器
	Os              string `json:"os,optional"`              //操作信息
}

type QueryOperateLogListResp struct {
	Code     string                     `json:"code"`
	Message  string                     `json:"message"`
	Current  int64                      `json:"current,default=1"`
	Data     []*QueryOperateLogListData `json:"data"`
	PageSize int64                      `json:"pageSize,default=20"`
	Success  bool                       `json:"success"`
	Total    int64                      `json:"total"`
}

type QueryPostDetailData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	Id         int64  `json:"id"`         //编号
	PostCode   string `json:"postCode"`   //岗位编码
	PostName   string `json:"postName"`   //岗位名称
	PostSort   int32  `json:"postSort"`   //岗位排序
	PostStatus int32  `json:"postStatus"` //岗位状态
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type QueryPostDetailReq struct {
	Id int64 `form:"id"`
}

type QueryPostDetailResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    QueryPostDetailData `json:"data"`
}

type QueryPostListData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	Id         int64  `json:"id"`         //编号
	PostCode   string `json:"postCode"`   //岗位编码
	PostName   string `json:"postName"`   //岗位名称
	PostSort   int32  `json:"postSort"`   //岗位排序
	PostStatus int32  `json:"postStatus"` //岗位状态
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type QueryPostListReq struct {
	Current    int64  `form:"current,default=1"`    //第几页
	PageSize   int64  `form:"pageSize,default=20"`  //每页的数量
	PostCode   string `form:"postCode,optional"`    //岗位编码
	PostName   string `form:"postName,optional"`    //岗位名称
	PostStatus int32  `form:"postStatus,default=2"` //岗位状态
}

type QueryPostListResp struct {
	Code     string               `json:"code"`
	Message  string               `json:"message"`
	Current  int64                `json:"current,default=1"`
	Data     []*QueryPostListData `json:"data"`
	PageSize int64                `json:"pageSize,default=20"`
	Success  bool                 `json:"success"`
	Total    int64                `json:"total"`
}

type QueryRoleDetailData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DataScope  int32  `json:"dataScope"`  //数据权限
	Id         int64  `json:"id"`         //编号
	IsAdmin    int32  `json:"isAdmin"`    //是否超级管理员
	Remark     string `json:"remark"`     //备注
	RoleKey    string `json:"roleKey"`    //权限字符
	RoleName   string `json:"roleName"`   //角色名称
	RoleSort   int32  `json:"roleSort"`   //角色排序
	RoleStatus int32  `json:"roleStatus"` //角色状态
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type QueryRoleDetailReq struct {
	Id int64 `form:"id"`
}

type QueryRoleDetailResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    QueryRoleDetailData `json:"data"`
}

type QueryRoleListData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DataScope  int32  `json:"dataScope"`  //数据权限
	Id         int64  `json:"id"`         //编号
	IsAdmin    int32  `json:"isAdmin"`    //是否超级管理员
	Remark     string `json:"remark"`     //备注
	RoleKey    string `json:"roleKey"`    //权限字符
	RoleName   string `json:"roleName"`   //角色名称
	RoleSort   int32  `json:"roleSort"`   //角色排序
	RoleStatus int32  `json:"roleStatus"` //角色状态
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type QueryRoleListReq struct {
	Current    int64  `form:"current,default=1"`    //第几页
	PageSize   int64  `form:"pageSize,default=20"`  //每页的数量
	IsAdmin    int32  `form:"isAdmin,default=2"`    //是否超级管理员
	RoleKey    string `form:"roleKey,optional"`     //权限字符
	RoleName   string `form:"roleName,optional"`    //角色名称
	RoleStatus int32  `form:"roleStatus,default=2"` //角色状态
}

type QueryRoleListResp struct {
	Code     string               `json:"code"`
	Message  string               `json:"message"`
	Current  int64                `json:"current,default=1"`
	Data     []*QueryRoleListData `json:"data"`
	PageSize int64                `json:"pageSize,default=20"`
	Success  bool                 `json:"success"`
	Total    int64                `json:"total"`
}

type QueryRoleMenuListReq struct {
	RoleId int64 `form:"roleId"`
}

type QueryRoleMenuListResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    RoleMenuListData `json:"data"`
}

type QueryRoleUserListData struct {
	Avatar     string `json:"avatar"`     //头像
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DeptId     int64  `json:"deptId"`     //部门id
	Email      string `json:"email"`      //邮箱
	Id         int64  `json:"id"`         //编号
	LoginIp    string `json:"loginIp"`    //登录ip
	LoginTime  string `json:"loginTime"`  //登录时间
	Mobile     string `json:"mobile"`     //手机号
	NickName   string `json:"nickName"`   //昵称
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
	UserName   string `json:"userName"`   //用户名
	UserStatus int32  `json:"userStatus"` //帐号状态（0正常 1停用）
}

type QueryRoleUserListReq struct {
	Current  int64  `form:"current,default=1"`   //第几页
	PageSize int64  `form:"pageSize,default=20"` //每页的数量
	RoleId   int64  `form:"roleId"`              //角色id
	IsExist  int64  `form:"isExist"`             //角色是否已经拥有用户
	Mobile   string `form:"mobile,optional"`     //手机号
	UserName string `form:"userName,optional"`   //昵称
}

type QueryRoleUserListResp struct {
	Code     string                   `json:"code"`
	Message  string                   `json:"message"`
	Current  int64                    `json:"current,default=1"`
	Data     []*QueryRoleUserListData `json:"data"`
	PageSize int64                    `json:"pageSize,default=20"`
	Success  bool                     `json:"success"`
	Total    int64                    `json:"total"`
}

type QueryStatisticsLoginLogData struct {
	DayLoginCount   int32 `json:"dayLoginCount"`   //查询当天登录人数（根据IP）
	WeekLoginCount  int32 `json:"weekLoginCount"`  //统计当前周登录人数（根据IP）
	MonthLoginCount int32 `json:"monthLoginCount"` //统计当前月登录人数（根据IP）
}

type QueryStatisticsLoginLogResp struct {
	Code    string                      `json:"code"`
	Message string                      `json:"message"`
	Data    QueryStatisticsLoginLogData `json:"data"`
}

type QueryUserDetailData struct {
	Avatar     string  `json:"avatar"`     //头像
	CreateBy   string  `json:"createBy"`   //创建者
	CreateTime string  `json:"createTime"` //创建时间
	DeptId     int64   `json:"deptId"`     //部门id
	Email      string  `json:"email"`      //邮箱
	Id         int64   `json:"id"`         //编号
	LoginIp    string  `json:"loginIp"`    //登录ip
	LoginTime  string  `json:"loginTime"`  //登录时间
	Mobile     string  `json:"mobile"`     //手机号
	NickName   string  `json:"nickName"`   //昵称
	Remark     string  `json:"remark"`     //备注信息
	Salt       string  `json:"salt"`       //加密盐
	UpdateBy   string  `json:"updateBy"`   //更新者
	UpdateTime string  `json:"updateTime"` //更新时间
	UserName   string  `json:"userName"`   //用户名
	UserStatus int32   `json:"userStatus"` //帐号状态（0正常 1停用）
	PostIds    []int64 `json:"postIds"`    //部门id
}

type QueryUserDetailReq struct {
	Id int64 `form:"id"`
}

type QueryUserDetailResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    QueryUserDetailData `json:"data"`
}

type QueryUserListData struct {
	Avatar     string `json:"avatar"`     //头像
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DeptId     int64  `json:"deptId"`     //部门id
	Email      string `json:"email"`      //邮箱
	Id         int64  `json:"id"`         //编号
	LoginIp    string `json:"loginIp"`    //登录ip
	LoginTime  string `json:"loginTime"`  //登录时间
	Mobile     string `json:"mobile"`     //手机号
	NickName   string `json:"nickName"`   //昵称
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
	UserName   string `json:"userName"`   //用户名
	UserStatus int32  `json:"userStatus"` //帐号状态（0正常 1停用）
}

type QueryUserListReq struct {
	Current    int64  `form:"current,default=1"`    //第几页
	PageSize   int64  `form:"pageSize,default=20"`  //每页的数量
	DeptId     int64  `form:"deptId,default=0"`     //部门id
	Email      string `form:"email,optional"`       //邮箱
	Mobile     string `form:"mobile,optional"`      //手机号
	NickName   string `form:"nickName,optional"`    //昵称
	UserStatus int32  `form:"userStatus,default=2"` //帐号状态（0正常 1停用）
}

type QueryUserListResp struct {
	Code     string               `json:"code"`
	Message  string               `json:"message"`
	Current  int64                `json:"current,default=1"`
	Data     []*QueryUserListData `json:"data"`
	PageSize int64                `json:"pageSize,default=20"`
	Success  bool                 `json:"success"`
	Total    int64                `json:"total"`
}

type QueryUserRoleListReq struct {
	UserId   int64  `form:"userId"`
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	RoleName string `json:"roleName,optional"` // 角色名称
	RoleKey  string `json:"roleKey,optional"`  //权限字符
}

type QueryUserRoleListResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    UserRoleListData `json:"data"`
}

type ReSetPasswordReq struct {
	UserId int64 `json:"userId"`
}

type ReSetPasswordResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type RoleListData struct {
	Id         int64  `json:"id"`         // 编号
	RoleName   string `json:"roleName"`   // 角色名称
	Remark     string `json:"remark"`     // 备注
	CreateBy   string `json:"createBy"`   // 创建人
	CreateTime string `json:"createTime"` // 创建时间
	UpdateBy   string `json:"updateBy"`   // 更新人
	UpdateTime string `json:"updateTime"` // 更新时间
	RoleStatus int32  `json:"roleStatus"` // 状态
}

type RoleMenuListData struct {
	MenuList []MenuTreeListData `json:"menuList"`
	MenuIds  []int64            `json:"menuIds"`
}

type UpdateDeptReq struct {
	DeptName   string  `json:"deptName"`        //部门名称
	DeptSort   int32   `json:"deptSort"`        //部门排序
	DeptStatus int32   `json:"deptStatus"`      //部门状态
	Email      string  `json:"email"`           //邮箱
	Id         int64   `json:"id"`              //编号
	Leader     string  `json:"leader"`          //负责人
	ParentId   int64   `json:"parentId"`        //上级机构ID，一级机构为0
	ParentIds  []int64 `json:"parentIds"`       //上级机构IDs，一级机构为0
	Phone      string  `json:"phone"`           //电话号码
	Remark     string  `json:"remark,optional"` //备注信息
}

type UpdateDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateDeptStatusReq struct {
	DeptStatus int32   `json:"deptStatus"` //部门状态
	DeptIds    []int64 `json:"deptIds"`    //编号
}

type UpdateDeptStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateDictItemReq struct {
	DictLabel  string `json:"dictLabel"`       //字典标签
	DictSort   int32  `json:"dictSort"`        //排序
	DictStatus int32  `json:"dictStatus"`      //字典状态
	DictType   string `json:"dictType"`        //字典类型
	DictValue  string `json:"dictValue"`       //字典键值
	Id         int64  `json:"id"`              //编号
	IsDefault  int32  `json:"isDefault"`       //是否默认  0：否  1：是
	Remark     string `json:"remark,optional"` //备注信息
}

type UpdateDictItemResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateDictItemStatusReq struct {
	DictStatus int32   `json:"dictStatus"` //字典状态
	DictIds    []int64 `json:"dictIds"`    //编号
}

type UpdateDictItemStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateDictTypeReq struct {
	DictName   string `json:"dictName"`        //字典名称
	DictStatus int32  `json:"dictStatus"`      //字典状态
	DictType   string `json:"dictType"`        //字典类型
	Id         int64  `json:"id"`              //编号
	IsSystem   int32  `json:"isSystem"`        //是否系统预留  0：否  1：是
	Remark     string `json:"remark,optional"` //备注信息
}

type UpdateDictTypeResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateDictTypeStatusReq struct {
	DictStatus int32   `json:"dictStatus"` //字典状态
	DictIds    []int64 `json:"dictIds"`    //编号
}

type UpdateDictTypeStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateMenuReq struct {
	Id            int64  `json:"id"`                     //编号
	BackgroundUrl string `json:"backgroundUrl,optional"` //接口地址
	MenuIcon      string `json:"menuIcon,optional"`      //菜单图标
	MenuName      string `json:"menuName"`               //菜单名称
	MenuPath      string `json:"menuPath,optional"`      //前端路由
	MenuPerms     string `json:"menuPerms,optional"`     //权限标识
	MenuSort      int32  `json:"menuSort,optional"`      //菜单排序
	MenuStatus    int32  `json:"menuStatus,optional"`    //菜单状态
	MenuType      int32  `json:"menuType,optional"`      //类型 0：目录,1：菜单,2：按钮,3：外链
	ParentId      int64  `json:"parentId,optional"`      //父菜单ID，一级菜单为0
	Remark        string `json:"remark,optional"`        //备注信息
	VueComponent  string `json:"vueComponent,optional"`  //vue的页面
	VueIcon       string `json:"vueIcon,optional"`       //vue的图标
	VuePath       string `json:"vuePath,optional"`       //vue系统的path
	VueRedirect   string `json:"vueRedirect,optional"`   //vue的路由重定向
	IsVisible     int32  `json:"isVisible,default=1"`    //是否可见  0：否  1：是
}

type UpdateMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateMenuStatusReq struct {
	MenuIds    []int64 `json:"menuIds"`    //编号
	MenuStatus int32   `json:"menuStatus"` //菜单状态
}

type UpdateMenuStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdatePostReq struct {
	Id         int64  `json:"id"`              //编号
	PostCode   string `json:"postCode"`        //岗位编码
	PostName   string `json:"postName"`        //岗位名称
	PostSort   int32  `json:"postSort"`        //岗位排序
	PostStatus int32  `json:"postStatus"`      //岗位状态
	Remark     string `json:"remark,optional"` //备注信息
}

type UpdatePostResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdatePostStatusReq struct {
	PostIds    []int64 `json:"postIds"`    //编号
	PostStatus int32   `json:"postStatus"` //岗位状态
}

type UpdatePostStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateRoleMenuListReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type UpdateRoleMenuListResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateRoleReq struct {
	DataScope  int32  `json:"dataScope,default=0"` //数据权限
	Id         int64  `json:"id"`                  //编号
	IsAdmin    int32  `json:"isAdmin,default=0"`   //是否超级管理员
	Remark     string `json:"remark,optional"`     //备注
	RoleKey    string `json:"roleKey"`             //权限字符
	RoleName   string `json:"roleName"`            //角色名称
	RoleSort   int32  `json:"roleSort"`            //角色排序
	RoleStatus int32  `json:"roleStatus"`          //角色状态
}

type UpdateRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateRoleStatusReq struct {
	RoleIds    []int64 `json:"roleIds"`    //编号
	RoleStatus int32   `json:"roleStatus"` //角色状态
}

type UpdateRoleStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateUserReq struct {
	Avatar     string  `json:"avatar,optional"`  //头像
	DeptId     int64   `json:"deptId,optional"`  //部门id
	PostIds    []int64 `json:"postIds,optional"` //部门id
	Email      string  `json:"email"`            //邮箱
	Id         int64   `json:"id"`               //编号
	Mobile     string  `json:"mobile"`           //手机号
	NickName   string  `json:"nickName"`         //昵称
	Remark     string  `json:"remark,optional"`  //备注信息
	UserName   string  `json:"userName"`         //用户名
	UserStatus int32   `json:"userStatus"`       //帐号状态（0正常 1停用）
}

type UpdateUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateUserRoleReq struct {
	UserId  int64   `json:"userId"`
	RoleIds []int64 `json:"roleIds"`
}

type UpdateUserRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateUserStatusReq struct {
	UserIds    []int64 `json:"userIds"`    //编号
	UserStatus int32   `json:"userStatus"` //帐号状态（0正常 1停用）
}

type UpdateUserStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UploadResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type UserInfoData struct {
	Avatar      string             `json:"avatar"`
	Name        string             `json:"name"`
	MenuTree    []*ListMenuTree    `json:"menuTree"`
	MenuTreeVue []*ListMenuTreeVue `json:"menuTreeVue"`
}

type UserProfileData struct {
	Avatar   string `json:"avatar"`
	Username string `json:"username"`
	NickName string `json:"nickname"`
	Email    string `json:"email"`
	Remark   string `json:"remark"`
	Phone    string `json:"phone"`
}

type UserRoleListData struct {
	RoleList []RoleListData `json:"roleList"`
	RoleIds  []int64        `json:"roleIds"`
}

type UserInfoResp struct {
	Code    string       `json:"code"`
	Message string       `json:"message"`
	Data    UserInfoData `json:"data"`
}

type UserProfileResp struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    UserProfileData `json:"data"`
}
