// Code generated by goctl. DO NOT EDIT.
// Source: record.proto

package server

import (
	"context"

	"github.com/summer-gonner/traffica/record/internal/logic/esservice"
	"github.com/summer-gonner/traffica/record/internal/svc"
	"github.com/summer-gonner/traffica/record/recordclient"
)

type EsServiceServer struct {
	svcCtx *svc.ServiceContext
	recordclient.UnimplementedEsServiceServer
}

func NewEsServiceServer(svcCtx *svc.ServiceContext) *EsServiceServer {
	return &EsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *EsServiceServer) EsConnect(ctx context.Context, in *recordclient.EsReq) (*recordclient.EsResp, error) {
	l := esservicelogic.NewEsConnectLogic(ctx, s.svcCtx)
	return l.EsConnect(in)
}
