// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"
	"github.com/summer-gonner/traffica/sys/internal/logic/deptservice"
	"github.com/summer-gonner/traffica/sys/internal/svc"
	sysclient2 "github.com/summer-gonner/traffica/sys/sysclient"
)

type DeptServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient2.UnimplementedDeptServiceServer
}

func NewDeptServiceServer(svcCtx *svc.ServiceContext) *DeptServiceServer {
	return &DeptServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加部门信息表
func (s *DeptServiceServer) AddDept(ctx context.Context, in *sysclient2.AddDeptReq) (*sysclient2.AddDeptResp, error) {
	l := deptservicelogic.NewAddDeptLogic(ctx, s.svcCtx)
	return l.AddDept(in)
}

// 删除部门信息表
func (s *DeptServiceServer) DeleteDept(ctx context.Context, in *sysclient2.DeleteDeptReq) (*sysclient2.DeleteDeptResp, error) {
	l := deptservicelogic.NewDeleteDeptLogic(ctx, s.svcCtx)
	return l.DeleteDept(in)
}

// 更新部门信息表
func (s *DeptServiceServer) UpdateDept(ctx context.Context, in *sysclient2.UpdateDeptReq) (*sysclient2.UpdateDeptResp, error) {
	l := deptservicelogic.NewUpdateDeptLogic(ctx, s.svcCtx)
	return l.UpdateDept(in)
}

// 更新部门信息表状态
func (s *DeptServiceServer) UpdateDeptStatus(ctx context.Context, in *sysclient2.UpdateDeptStatusReq) (*sysclient2.UpdateDeptStatusResp, error) {
	l := deptservicelogic.NewUpdateDeptStatusLogic(ctx, s.svcCtx)
	return l.UpdateDeptStatus(in)
}

// 查询部门信息表详情
func (s *DeptServiceServer) QueryDeptDetail(ctx context.Context, in *sysclient2.QueryDeptDetailReq) (*sysclient2.QueryDeptDetailResp, error) {
	l := deptservicelogic.NewQueryDeptDetailLogic(ctx, s.svcCtx)
	return l.QueryDeptDetail(in)
}

// 查询部门信息表列表
func (s *DeptServiceServer) QueryDeptList(ctx context.Context, in *sysclient2.QueryDeptListReq) (*sysclient2.QueryDeptListResp, error) {
	l := deptservicelogic.NewQueryDeptListLogic(ctx, s.svcCtx)
	return l.QueryDeptList(in)
}
