// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"
	"github.com/summmer-gonner/traffica/sys/internal/logic/postservice"
	"github.com/summmer-gonner/traffica/sys/internal/svc"
	sysclient2 "github.com/summmer-gonner/traffica/sys/sysclient"
)

type PostServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient2.UnimplementedPostServiceServer
}

func NewPostServiceServer(svcCtx *svc.ServiceContext) *PostServiceServer {
	return &PostServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加岗位管理
func (s *PostServiceServer) AddPost(ctx context.Context, in *sysclient2.AddPostReq) (*sysclient2.AddPostResp, error) {
	l := postservicelogic.NewAddPostLogic(ctx, s.svcCtx)
	return l.AddPost(in)
}

// 删除岗位管理
func (s *PostServiceServer) DeletePost(ctx context.Context, in *sysclient2.DeletePostReq) (*sysclient2.DeletePostResp, error) {
	l := postservicelogic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

// 更新岗位管理
func (s *PostServiceServer) UpdatePost(ctx context.Context, in *sysclient2.UpdatePostReq) (*sysclient2.UpdatePostResp, error) {
	l := postservicelogic.postservicelogic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

// 更新岗位管理状态
func (s *PostServiceServer) UpdatePostStatus(ctx context.Context, in *sysclient2.UpdatePostStatusReq) (*sysclient2.UpdatePostStatusResp, error) {
	l := postservicelogic.NewUpdatePostStatusLogic(ctx, s.svcCtx)
	return l.UpdatePostStatus(in)
}

// 查询岗位管理详情
func (s *PostServiceServer) QueryPostDetail(ctx context.Context, in *sysclient2.QueryPostDetailReq) (*sysclient2.QueryPostDetailResp, error) {
	l := postservicelogic.NewQueryPostDetailLogic(ctx, s.svcCtx)
	return l.QueryPostDetail(in)
}

// 查询岗位管理列表
func (s *PostServiceServer) QueryPostList(ctx context.Context, in *sysclient2.QueryPostListReq) (*sysclient2.QueryPostListResp, error) {
	l := postservicelogic.NewQueryPostListLogic(ctx, s.svcCtx)
	return l.QueryPostList(in)
}
