// Code generated by goctl. DO NOT EDIT.
package types

type AgentHeartBeatData struct {
	TimeStamp string `json:"timeStamp"`
}

type AgentHeartBeatResp struct {
	Code    string             `json:"code"`
	Message string             `json:"message"`
	Data    AgentHeartBeatData `json:"data"`
}
