// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: record/record.proto

package recordclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EsConnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EsConnectReq) Reset() {
	*x = EsConnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsConnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsConnectReq) ProtoMessage() {}

func (x *EsConnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsConnectReq.ProtoReflect.Descriptor instead.
func (*EsConnectReq) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{0}
}

func (x *EsConnectReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EsConnectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EsConnectResp) Reset() {
	*x = EsConnectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsConnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsConnectResp) ProtoMessage() {}

func (x *EsConnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsConnectResp.ProtoReflect.Descriptor instead.
func (*EsConnectResp) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{1}
}

func (x *EsConnectResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EsConnectResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EsAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *EsAddReq) Reset() {
	*x = EsAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsAddReq) ProtoMessage() {}

func (x *EsAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsAddReq.ProtoReflect.Descriptor instead.
func (*EsAddReq) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{2}
}

func (x *EsAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EsAddReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EsAddReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EsAddReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EsAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EsAddResp) Reset() {
	*x = EsAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsAddResp) ProtoMessage() {}

func (x *EsAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsAddResp.ProtoReflect.Descriptor instead.
func (*EsAddResp) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{3}
}

func (x *EsAddResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *EsAddResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EsQueryListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentPage int32  `protobuf:"varint,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize    int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address     string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *EsQueryListReq) Reset() {
	*x = EsQueryListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_record_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsQueryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsQueryListReq) ProtoMessage() {}

func (x *EsQueryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsQueryListReq.ProtoReflect.Descriptor instead.
func (*EsQueryListReq) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{4}
}

func (x *EsQueryListReq) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *EsQueryListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *EsQueryListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EsQueryListReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EsQueryInfoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address     string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Username    string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Remark      string `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	Result      string `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	ConnectTime string `protobuf:"bytes,8,opt,name=connect_time,json=connectTime,proto3" json:"connect_time,omitempty"`
	CreateBy    string `protobuf:"bytes,9,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreateTime  string `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateBy    string `protobuf:"bytes,11,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	UpdateTime  string `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *EsQueryInfoData) Reset() {
	*x = EsQueryInfoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_record_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsQueryInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsQueryInfoData) ProtoMessage() {}

func (x *EsQueryInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsQueryInfoData.ProtoReflect.Descriptor instead.
func (*EsQueryInfoData) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{5}
}

func (x *EsQueryInfoData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EsQueryInfoData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EsQueryInfoData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EsQueryInfoData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EsQueryInfoData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EsQueryInfoData) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *EsQueryInfoData) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *EsQueryInfoData) GetConnectTime() string {
	if x != nil {
		return x.ConnectTime
	}
	return ""
}

func (x *EsQueryInfoData) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *EsQueryInfoData) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *EsQueryInfoData) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *EsQueryInfoData) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type EsQueryListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentPage int32              `protobuf:"varint,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize    int32              `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalSize   int64              `protobuf:"varint,3,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	TotalPages  int64              `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	Records     []*EsQueryInfoData `protobuf:"bytes,5,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *EsQueryListData) Reset() {
	*x = EsQueryListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_record_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsQueryListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsQueryListData) ProtoMessage() {}

func (x *EsQueryListData) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsQueryListData.ProtoReflect.Descriptor instead.
func (*EsQueryListData) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{6}
}

func (x *EsQueryListData) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *EsQueryListData) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *EsQueryListData) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *EsQueryListData) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *EsQueryListData) GetRecords() []*EsQueryInfoData {
	if x != nil {
		return x.Records
	}
	return nil
}

type EsQueryListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *EsQueryListData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EsQueryListResp) Reset() {
	*x = EsQueryListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_record_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsQueryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsQueryListResp) ProtoMessage() {}

func (x *EsQueryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_record_record_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsQueryListResp.ProtoReflect.Descriptor instead.
func (*EsQueryListResp) Descriptor() ([]byte, []int) {
	return file_record_record_proto_rawDescGZIP(), []int{7}
}

func (x *EsQueryListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EsQueryListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EsQueryListResp) GetData() *EsQueryListData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_record_record_proto protoreflect.FileDescriptor

var file_record_record_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x45, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0d, 0x45, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x70, 0x0a, 0x08, 0x45, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x3d, 0x0a, 0x09, 0x45, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x7c, 0x0a, 0x0e, 0x45, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0xd6, 0x02, 0x0a, 0x0f, 0x45, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xc6, 0x01, 0x0a, 0x0f, 0x45,
	0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x73, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x22, 0x72, 0x0a, 0x0f, 0x45, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x45, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xd7, 0x01, 0x0a, 0x09, 0x45, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x45, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x12, 0x1a, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x45, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x73,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x05, 0x45,
	0x73, 0x41, 0x64, 0x64, 0x12, 0x16, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x73, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4a, 0x0a, 0x0b, 0x45, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x45, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_record_record_proto_rawDescOnce sync.Once
	file_record_record_proto_rawDescData = file_record_record_proto_rawDesc
)

func file_record_record_proto_rawDescGZIP() []byte {
	file_record_record_proto_rawDescOnce.Do(func() {
		file_record_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_record_record_proto_rawDescData)
	})
	return file_record_record_proto_rawDescData
}

var file_record_record_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_record_record_proto_goTypes = []any{
	(*EsConnectReq)(nil),    // 0: recordclient.EsConnectReq
	(*EsConnectResp)(nil),   // 1: recordclient.EsConnectResp
	(*EsAddReq)(nil),        // 2: recordclient.EsAddReq
	(*EsAddResp)(nil),       // 3: recordclient.EsAddResp
	(*EsQueryListReq)(nil),  // 4: recordclient.EsQueryListReq
	(*EsQueryInfoData)(nil), // 5: recordclient.EsQueryInfoData
	(*EsQueryListData)(nil), // 6: recordclient.EsQueryListData
	(*EsQueryListResp)(nil), // 7: recordclient.EsQueryListResp
}
var file_record_record_proto_depIdxs = []int32{
	5, // 0: recordclient.EsQueryListData.records:type_name -> recordclient.EsQueryInfoData
	6, // 1: recordclient.EsQueryListResp.data:type_name -> recordclient.EsQueryListData
	0, // 2: recordclient.EsService.EsConnect:input_type -> recordclient.EsConnectReq
	2, // 3: recordclient.EsService.EsAdd:input_type -> recordclient.EsAddReq
	4, // 4: recordclient.EsService.EsQueryList:input_type -> recordclient.EsQueryListReq
	1, // 5: recordclient.EsService.EsConnect:output_type -> recordclient.EsConnectResp
	3, // 6: recordclient.EsService.EsAdd:output_type -> recordclient.EsAddResp
	7, // 7: recordclient.EsService.EsQueryList:output_type -> recordclient.EsQueryListResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_record_record_proto_init() }
func file_record_record_proto_init() {
	if File_record_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_record_record_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EsConnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_record_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EsConnectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_record_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EsAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_record_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*EsAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_record_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EsQueryListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_record_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EsQueryInfoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_record_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EsQueryListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_record_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EsQueryListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_record_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_record_record_proto_goTypes,
		DependencyIndexes: file_record_record_proto_depIdxs,
		MessageInfos:      file_record_record_proto_msgTypes,
	}.Build()
	File_record_record_proto = out.File
	file_record_record_proto_rawDesc = nil
	file_record_record_proto_goTypes = nil
	file_record_record_proto_depIdxs = nil
}
