// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: record/record.proto

package recordclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EsService_EsConnect_FullMethodName   = "/recordclient.EsService/EsConnect"
	EsService_EsAdd_FullMethodName       = "/recordclient.EsService/EsAdd"
	EsService_EsQueryList_FullMethodName = "/recordclient.EsService/EsQueryList"
)

// EsServiceClient is the client API for EsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EsServiceClient interface {
	EsConnect(ctx context.Context, in *EsConnectReq, opts ...grpc.CallOption) (*EsConnectResp, error)
	EsAdd(ctx context.Context, in *EsAddReq, opts ...grpc.CallOption) (*EsAddResp, error)
	EsQueryList(ctx context.Context, in *EsQueryListReq, opts ...grpc.CallOption) (*EsQueryListResp, error)
}

type esServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEsServiceClient(cc grpc.ClientConnInterface) EsServiceClient {
	return &esServiceClient{cc}
}

func (c *esServiceClient) EsConnect(ctx context.Context, in *EsConnectReq, opts ...grpc.CallOption) (*EsConnectResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EsConnectResp)
	err := c.cc.Invoke(ctx, EsService_EsConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *esServiceClient) EsAdd(ctx context.Context, in *EsAddReq, opts ...grpc.CallOption) (*EsAddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EsAddResp)
	err := c.cc.Invoke(ctx, EsService_EsAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *esServiceClient) EsQueryList(ctx context.Context, in *EsQueryListReq, opts ...grpc.CallOption) (*EsQueryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EsQueryListResp)
	err := c.cc.Invoke(ctx, EsService_EsQueryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EsServiceServer is the server API for EsService service.
// All implementations must embed UnimplementedEsServiceServer
// for forward compatibility
type EsServiceServer interface {
	EsConnect(context.Context, *EsConnectReq) (*EsConnectResp, error)
	EsAdd(context.Context, *EsAddReq) (*EsAddResp, error)
	EsQueryList(context.Context, *EsQueryListReq) (*EsQueryListResp, error)
	mustEmbedUnimplementedEsServiceServer()
}

// UnimplementedEsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEsServiceServer struct {
}

func (UnimplementedEsServiceServer) EsConnect(context.Context, *EsConnectReq) (*EsConnectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EsConnect not implemented")
}
func (UnimplementedEsServiceServer) EsAdd(context.Context, *EsAddReq) (*EsAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EsAdd not implemented")
}
func (UnimplementedEsServiceServer) EsQueryList(context.Context, *EsQueryListReq) (*EsQueryListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EsQueryList not implemented")
}
func (UnimplementedEsServiceServer) mustEmbedUnimplementedEsServiceServer() {}

// UnsafeEsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EsServiceServer will
// result in compilation errors.
type UnsafeEsServiceServer interface {
	mustEmbedUnimplementedEsServiceServer()
}

func RegisterEsServiceServer(s grpc.ServiceRegistrar, srv EsServiceServer) {
	s.RegisterService(&EsService_ServiceDesc, srv)
}

func _EsService_EsConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EsConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsServiceServer).EsConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EsService_EsConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsServiceServer).EsConnect(ctx, req.(*EsConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EsService_EsAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EsAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsServiceServer).EsAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EsService_EsAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsServiceServer).EsAdd(ctx, req.(*EsAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EsService_EsQueryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EsQueryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsServiceServer).EsQueryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EsService_EsQueryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsServiceServer).EsQueryList(ctx, req.(*EsQueryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EsService_ServiceDesc is the grpc.ServiceDesc for EsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recordclient.EsService",
	HandlerType: (*EsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EsConnect",
			Handler:    _EsService_EsConnect_Handler,
		},
		{
			MethodName: "EsAdd",
			Handler:    _EsService_EsAdd_Handler,
		},
		{
			MethodName: "EsQueryList",
			Handler:    _EsService_EsQueryList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "record/record.proto",
}
