// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"
	"github.com/summmer-gonner/traffica/sys/internal/logic/menuservice"
	"github.com/summmer-gonner/traffica/sys/internal/svc"
	sysclient2 "github.com/summmer-gonner/traffica/sys/sysclient"
)

type MenuServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient2.UnimplementedMenuServiceServer
}

func NewMenuServiceServer(svcCtx *svc.ServiceContext) *MenuServiceServer {
	return &MenuServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加菜单信息表
func (s *MenuServiceServer) AddMenu(ctx context.Context, in *sysclient2.AddMenuReq) (*sysclient2.AddMenuResp, error) {
	l := menuservicelogic.NewAddMenuLogic(ctx, s.svcCtx)
	return l.AddMenu(in)
}

// 删除菜单信息表
func (s *MenuServiceServer) DeleteMenu(ctx context.Context, in *sysclient2.DeleteMenuReq) (*sysclient2.DeleteMenuResp, error) {
	l := menuservicelogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

// 更新菜单信息表
func (s *MenuServiceServer) UpdateMenu(ctx context.Context, in *sysclient2.UpdateMenuReq) (*sysclient2.UpdateMenuResp, error) {
	l := menuservicelogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

// 更新菜单信息表状态
func (s *MenuServiceServer) UpdateMenuStatus(ctx context.Context, in *sysclient2.UpdateMenuStatusReq) (*sysclient2.UpdateMenuStatusResp, error) {
	l := menuservicelogic.NewUpdateMenuStatusLogic(ctx, s.svcCtx)
	return l.UpdateMenuStatus(in)
}

// 查询菜单信息表详情
func (s *MenuServiceServer) QueryMenuDetail(ctx context.Context, in *sysclient2.QueryMenuDetailReq) (*sysclient2.QueryMenuDetailResp, error) {
	l := menuservicelogic.NewQueryMenuDetailLogic(ctx, s.svcCtx)
	return l.QueryMenuDetail(in)
}

// 查询菜单信息表列表
func (s *MenuServiceServer) QueryMenuList(ctx context.Context, in *sysclient2.QueryMenuListReq) (*sysclient2.QueryMenuListResp, error) {
	l := menuservicelogic.menuservicelogic.NewQueryMenuListLogic(ctx, s.svcCtx)
	return l.QueryMenuList(in)
}
