apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  namespace: zero-admin
  labels:
    app: admin-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      serviceAccountName: koobe
      containers:
        - name: admin-api
          image: admin-api:0.0.1
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: zero-admin-config

---
apiVersion: v1
kind: Service
metadata:
  name: admin-api-svc
  namespace: zero-admin
  labels:
    app: admin-api-svc
spec:
  ports:
    - port: 8888
      name: admin-api
      targetPort: 8888
  selector:
    app: admin-api
  type: NodePort
