apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-rpc
  namespace: zero-admin
  labels:
    app: cms-rpc
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cms-rpc
  template:
    metadata:
      labels:
        app: cms-rpc
    spec:
      containers:
        - name: cms-rpc
          image: cms-rpc:0.0.1
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: zero-admin-config

---
apiVersion: v1
kind: Service
metadata:
  name: cms-rpc-svc
  namespace: zero-admin
  labels:
    app: cms-rpc-svc
spec:
  ports:
    - port: 8086
      name: cms-rpc
      targetPort: 8086
  selector:
    app: cms-rpc
