apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-rpc
  namespace: zero-admin
  labels:
    app: sms-rpc
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sms-rpc
  template:
    metadata:
      labels:
        app: sms-rpc
    spec:
      containers:
        - name: sms-rpc
          image: sms-rpc:0.0.1
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: zero-admin-config

---
apiVersion: v1
kind: Service
metadata:
  name: sms-rpc-svc
  namespace: zero-admin
  labels:
    app: sms-rpc-svc
spec:
  ports:
    - port: 8084
      name: sms-rpc
      targetPort: 8084
  selector:
    app: sms-rpc
