// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package loginlogservice

import (
	"context"
	sysclient2 "github.com/summmer-gonner/traffica/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddDeptReq                = sysclient2.AddDeptReq
	AddDeptResp               = sysclient2.AddDeptResp
	AddDictItemReq            = sysclient2.AddDictItemReq
	AddDictItemResp           = sysclient2.AddDictItemResp
	AddDictTypeReq            = sysclient2.AddDictTypeReq
	AddDictTypeResp           = sysclient2.AddDictTypeResp
	AddMenuReq                = sysclient2.AddMenuReq
	AddMenuResp               = sysclient2.AddMenuResp
	AddOperateLogReq          = sysclient2.AddOperateLogReq
	AddOperateLogResp         = sysclient2.AddOperateLogResp
	AddPostReq                = sysclient2.AddPostReq
	AddPostResp               = sysclient2.AddPostResp
	AddRoleReq                = sysclient2.AddRoleReq
	AddRoleResp               = sysclient2.AddRoleResp
	AddUserReq                = sysclient2.AddUserReq
	AddUserResp               = sysclient2.AddUserResp
	CancelAuthorizationReq    = sysclient2.CancelAuthorizationReq
	CancelAuthorizationResp   = sysclient2.CancelAuthorizationResp
	DeleteDeptReq             = sysclient2.DeleteDeptReq
	DeleteDeptResp            = sysclient2.DeleteDeptResp
	DeleteDictItemReq         = sysclient2.DeleteDictItemReq
	DeleteDictItemResp        = sysclient2.DeleteDictItemResp
	DeleteDictTypeReq         = sysclient2.DeleteDictTypeReq
	DeleteDictTypeResp        = sysclient2.DeleteDictTypeResp
	DeleteLoginLogReq         = sysclient2.DeleteLoginLogReq
	DeleteLoginLogResp        = sysclient2.DeleteLoginLogResp
	DeleteMenuReq             = sysclient2.DeleteMenuReq
	DeleteMenuResp            = sysclient2.DeleteMenuResp
	DeleteOperateLogReq       = sysclient2.DeleteOperateLogReq
	DeleteOperateLogResp      = sysclient2.DeleteOperateLogResp
	DeletePostReq             = sysclient2.DeletePostReq
	DeletePostResp            = sysclient2.DeletePostResp
	DeleteRoleReq             = sysclient2.DeleteRoleReq
	DeleteRoleResp            = sysclient2.DeleteRoleResp
	DeleteUserReq             = sysclient2.DeleteUserReq
	DeleteUserResp            = sysclient2.DeleteUserResp
	DeptData                  = sysclient2.DeptData
	DeptListData              = sysclient2.DeptListData
	DictItemListData          = sysclient2.DictItemListData
	DictTypeListData          = sysclient2.DictTypeListData
	InfoReq                   = sysclient2.InfoReq
	InfoResp                  = sysclient2.InfoResp
	LoginLogListData          = sysclient2.LoginLogListData
	LoginReq                  = sysclient2.LoginReq
	LoginResp                 = sysclient2.LoginResp
	MenuData                  = sysclient2.MenuData
	MenuListData              = sysclient2.MenuListData
	MenuListTree              = sysclient2.MenuListTree
	OperateLogListData        = sysclient2.OperateLogListData
	PostData                  = sysclient2.PostData
	PostListData              = sysclient2.PostListData
	QueryDeptAndPostListReq   = sysclient2.QueryDeptAndPostListReq
	QueryDeptAndPostListResp  = sysclient2.QueryDeptAndPostListResp
	QueryDeptDetailReq        = sysclient2.QueryDeptDetailReq
	QueryDeptDetailResp       = sysclient2.QueryDeptDetailResp
	QueryDeptListReq          = sysclient2.QueryDeptListReq
	QueryDeptListResp         = sysclient2.QueryDeptListResp
	QueryDictItemDetailReq    = sysclient2.QueryDictItemDetailReq
	QueryDictItemDetailResp   = sysclient2.QueryDictItemDetailResp
	QueryDictItemListReq      = sysclient2.QueryDictItemListReq
	QueryDictItemListResp     = sysclient2.QueryDictItemListResp
	QueryDictTypeDetailReq    = sysclient2.QueryDictTypeDetailReq
	QueryDictTypeDetailResp   = sysclient2.QueryDictTypeDetailResp
	QueryDictTypeListReq      = sysclient2.QueryDictTypeListReq
	QueryDictTypeListResp     = sysclient2.QueryDictTypeListResp
	QueryLoginLogDetailReq    = sysclient2.QueryLoginLogDetailReq
	QueryLoginLogDetailResp   = sysclient2.QueryLoginLogDetailResp
	QueryLoginLogListReq      = sysclient2.QueryLoginLogListReq
	QueryLoginLogListResp     = sysclient2.QueryLoginLogListResp
	QueryMenuDetailReq        = sysclient2.QueryMenuDetailReq
	QueryMenuDetailResp       = sysclient2.QueryMenuDetailResp
	QueryMenuListReq          = sysclient2.QueryMenuListReq
	QueryMenuListResp         = sysclient2.QueryMenuListResp
	QueryOperateLogDetailReq  = sysclient2.QueryOperateLogDetailReq
	QueryOperateLogDetailResp = sysclient2.QueryOperateLogDetailResp
	QueryOperateLogListReq    = sysclient2.QueryOperateLogListReq
	QueryOperateLogListResp   = sysclient2.QueryOperateLogListResp
	QueryPostDetailReq        = sysclient2.QueryPostDetailReq
	QueryPostDetailResp       = sysclient2.QueryPostDetailResp
	QueryPostListReq          = sysclient2.QueryPostListReq
	QueryPostListResp         = sysclient2.QueryPostListResp
	QueryRoleDetailReq        = sysclient2.QueryRoleDetailReq
	QueryRoleDetailResp       = sysclient2.QueryRoleDetailResp
	QueryRoleListReq          = sysclient2.QueryRoleListReq
	QueryRoleListResp         = sysclient2.QueryRoleListResp
	QueryRoleMenuListReq      = sysclient2.QueryRoleMenuListReq
	QueryRoleMenuListResp     = sysclient2.QueryRoleMenuListResp
	QueryRoleUserListReq      = sysclient2.QueryRoleUserListReq
	QueryRoleUserListResp     = sysclient2.QueryRoleUserListResp
	QueryUserDetailReq        = sysclient2.QueryUserDetailReq
	QueryUserDetailResp       = sysclient2.QueryUserDetailResp
	QueryUserListReq          = sysclient2.QueryUserListReq
	QueryUserListResp         = sysclient2.QueryUserListResp
	QueryUserRoleListReq      = sysclient2.QueryUserRoleListReq
	QueryUserRoleListResp     = sysclient2.QueryUserRoleListResp
	ReSetPasswordReq          = sysclient2.ReSetPasswordReq
	ReSetPasswordResp         = sysclient2.ReSetPasswordResp
	RoleData                  = sysclient2.RoleData
	RoleListData              = sysclient2.RoleListData
	UpdateDeptReq             = sysclient2.UpdateDeptReq
	UpdateDeptResp            = sysclient2.UpdateDeptResp
	UpdateDeptStatusReq       = sysclient2.UpdateDeptStatusReq
	UpdateDeptStatusResp      = sysclient2.UpdateDeptStatusResp
	UpdateDictItemReq         = sysclient2.UpdateDictItemReq
	UpdateDictItemResp        = sysclient2.UpdateDictItemResp
	UpdateDictItemStatusReq   = sysclient2.UpdateDictItemStatusReq
	UpdateDictItemStatusResp  = sysclient2.UpdateDictItemStatusResp
	UpdateDictTypeReq         = sysclient2.UpdateDictTypeReq
	UpdateDictTypeResp        = sysclient2.UpdateDictTypeResp
	UpdateDictTypeStatusReq   = sysclient2.UpdateDictTypeStatusReq
	UpdateDictTypeStatusResp  = sysclient2.UpdateDictTypeStatusResp
	UpdateMenuReq             = sysclient2.UpdateMenuReq
	UpdateMenuResp            = sysclient2.UpdateMenuResp
	UpdateMenuRoleReq         = sysclient2.UpdateMenuRoleReq
	UpdateMenuRoleResp        = sysclient2.UpdateMenuRoleResp
	UpdateMenuStatusReq       = sysclient2.UpdateMenuStatusReq
	UpdateMenuStatusResp      = sysclient2.UpdateMenuStatusResp
	UpdatePostReq             = sysclient2.UpdatePostReq
	UpdatePostResp            = sysclient2.UpdatePostResp
	UpdatePostStatusReq       = sysclient2.UpdatePostStatusReq
	UpdatePostStatusResp      = sysclient2.UpdatePostStatusResp
	UpdateRoleReq             = sysclient2.UpdateRoleReq
	UpdateRoleResp            = sysclient2.UpdateRoleResp
	UpdateRoleStatusReq       = sysclient2.UpdateRoleStatusReq
	UpdateRoleStatusResp      = sysclient2.UpdateRoleStatusResp
	UpdateUserReq             = sysclient2.UpdateUserReq
	UpdateUserResp            = sysclient2.UpdateUserResp
	UpdateUserRoleListReq     = sysclient2.UpdateUserRoleListReq
	UpdateUserRoleListResp    = sysclient2.UpdateUserRoleListResp
	UpdateUserStatusReq       = sysclient2.UpdateUserStatusReq
	UpdateUserStatusResp      = sysclient2.UpdateUserStatusResp
	UserData                  = sysclient2.UserData
	UserListData              = sysclient2.UserListData

	LoginLogService interface {
		// 删除系统登录日志表
		DeleteLoginLog(ctx context.Context, in *DeleteLoginLogReq, opts ...grpc.CallOption) (*DeleteLoginLogResp, error)
		// 查询系统登录日志表详情
		QueryLoginLogDetail(ctx context.Context, in *QueryLoginLogDetailReq, opts ...grpc.CallOption) (*QueryLoginLogDetailResp, error)
		// 查询系统登录日志表列表
		QueryLoginLogList(ctx context.Context, in *QueryLoginLogListReq, opts ...grpc.CallOption) (*QueryLoginLogListResp, error)
	}

	defaultLoginLogService struct {
		cli zrpc.Client
	}
)

func NewLoginLogService(cli zrpc.Client) LoginLogService {
	return &defaultLoginLogService{
		cli: cli,
	}
}

// 删除系统登录日志表
func (m *defaultLoginLogService) DeleteLoginLog(ctx context.Context, in *DeleteLoginLogReq, opts ...grpc.CallOption) (*DeleteLoginLogResp, error) {
	client := sysclient2.NewLoginLogServiceClient(m.cli.Conn())
	return client.DeleteLoginLog(ctx, in, opts...)
}

// 查询系统登录日志表详情
func (m *defaultLoginLogService) QueryLoginLogDetail(ctx context.Context, in *QueryLoginLogDetailReq, opts ...grpc.CallOption) (*QueryLoginLogDetailResp, error) {
	client := sysclient2.NewLoginLogServiceClient(m.cli.Conn())
	return client.QueryLoginLogDetail(ctx, in, opts...)
}

// 查询系统登录日志表列表
func (m *defaultLoginLogService) QueryLoginLogList(ctx context.Context, in *QueryLoginLogListReq, opts ...grpc.CallOption) (*QueryLoginLogListResp, error) {
	client := sysclient2.NewLoginLogServiceClient(m.cli.Conn())
	return client.QueryLoginLogList(ctx, in, opts...)
}
