// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package userservice

import (
	"context"
	sysclient2 "github.com/summmer-gonner/traffica/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddDeptReq                = sysclient2.AddDeptReq
	AddDeptResp               = sysclient2.AddDeptResp
	AddDictItemReq            = sysclient2.AddDictItemReq
	AddDictItemResp           = sysclient2.AddDictItemResp
	AddDictTypeReq            = sysclient2.AddDictTypeReq
	AddDictTypeResp           = sysclient2.AddDictTypeResp
	AddMenuReq                = sysclient2.AddMenuReq
	AddMenuResp               = sysclient2.AddMenuResp
	AddOperateLogReq          = sysclient2.AddOperateLogReq
	AddOperateLogResp         = sysclient2.AddOperateLogResp
	AddPostReq                = sysclient2.AddPostReq
	AddPostResp               = sysclient2.AddPostResp
	AddRoleReq                = sysclient2.AddRoleReq
	AddRoleResp               = sysclient2.AddRoleResp
	AddUserReq                = sysclient2.AddUserReq
	AddUserResp               = sysclient2.AddUserResp
	CancelAuthorizationReq    = sysclient2.CancelAuthorizationReq
	CancelAuthorizationResp   = sysclient2.CancelAuthorizationResp
	DeleteDeptReq             = sysclient2.DeleteDeptReq
	DeleteDeptResp            = sysclient2.DeleteDeptResp
	DeleteDictItemReq         = sysclient2.DeleteDictItemReq
	DeleteDictItemResp        = sysclient2.DeleteDictItemResp
	DeleteDictTypeReq         = sysclient2.DeleteDictTypeReq
	DeleteDictTypeResp        = sysclient2.DeleteDictTypeResp
	DeleteLoginLogReq         = sysclient2.DeleteLoginLogReq
	DeleteLoginLogResp        = sysclient2.DeleteLoginLogResp
	DeleteMenuReq             = sysclient2.DeleteMenuReq
	DeleteMenuResp            = sysclient2.DeleteMenuResp
	DeleteOperateLogReq       = sysclient2.DeleteOperateLogReq
	DeleteOperateLogResp      = sysclient2.DeleteOperateLogResp
	DeletePostReq             = sysclient2.DeletePostReq
	DeletePostResp            = sysclient2.DeletePostResp
	DeleteRoleReq             = sysclient2.DeleteRoleReq
	DeleteRoleResp            = sysclient2.DeleteRoleResp
	DeleteUserReq             = sysclient2.DeleteUserReq
	DeleteUserResp            = sysclient2.DeleteUserResp
	DeptData                  = sysclient2.DeptData
	DeptListData              = sysclient2.DeptListData
	DictItemListData          = sysclient2.DictItemListData
	DictTypeListData          = sysclient2.DictTypeListData
	InfoReq                   = sysclient2.InfoReq
	InfoResp                  = sysclient2.InfoResp
	LoginLogListData          = sysclient2.LoginLogListData
	LoginReq                  = sysclient2.LoginReq
	LoginResp                 = sysclient2.LoginResp
	MenuData                  = sysclient2.MenuData
	MenuListData              = sysclient2.MenuListData
	MenuListTree              = sysclient2.MenuListTree
	OperateLogListData        = sysclient2.OperateLogListData
	PostData                  = sysclient2.PostData
	PostListData              = sysclient2.PostListData
	QueryDeptAndPostListReq   = sysclient2.QueryDeptAndPostListReq
	QueryDeptAndPostListResp  = sysclient2.QueryDeptAndPostListResp
	QueryDeptDetailReq        = sysclient2.QueryDeptDetailReq
	QueryDeptDetailResp       = sysclient2.QueryDeptDetailResp
	QueryDeptListReq          = sysclient2.QueryDeptListReq
	QueryDeptListResp         = sysclient2.QueryDeptListResp
	QueryDictItemDetailReq    = sysclient2.QueryDictItemDetailReq
	QueryDictItemDetailResp   = sysclient2.QueryDictItemDetailResp
	QueryDictItemListReq      = sysclient2.QueryDictItemListReq
	QueryDictItemListResp     = sysclient2.QueryDictItemListResp
	QueryDictTypeDetailReq    = sysclient2.QueryDictTypeDetailReq
	QueryDictTypeDetailResp   = sysclient2.QueryDictTypeDetailResp
	QueryDictTypeListReq      = sysclient2.QueryDictTypeListReq
	QueryDictTypeListResp     = sysclient2.QueryDictTypeListResp
	QueryLoginLogDetailReq    = sysclient2.QueryLoginLogDetailReq
	QueryLoginLogDetailResp   = sysclient2.QueryLoginLogDetailResp
	QueryLoginLogListReq      = sysclient2.QueryLoginLogListReq
	QueryLoginLogListResp     = sysclient2.QueryLoginLogListResp
	QueryMenuDetailReq        = sysclient2.QueryMenuDetailReq
	QueryMenuDetailResp       = sysclient2.QueryMenuDetailResp
	QueryMenuListReq          = sysclient2.QueryMenuListReq
	QueryMenuListResp         = sysclient2.QueryMenuListResp
	QueryOperateLogDetailReq  = sysclient2.QueryOperateLogDetailReq
	QueryOperateLogDetailResp = sysclient2.QueryOperateLogDetailResp
	QueryOperateLogListReq    = sysclient2.QueryOperateLogListReq
	QueryOperateLogListResp   = sysclient2.QueryOperateLogListResp
	QueryPostDetailReq        = sysclient2.QueryPostDetailReq
	QueryPostDetailResp       = sysclient2.QueryPostDetailResp
	QueryPostListReq          = sysclient2.QueryPostListReq
	QueryPostListResp         = sysclient2.QueryPostListResp
	QueryRoleDetailReq        = sysclient2.QueryRoleDetailReq
	QueryRoleDetailResp       = sysclient2.QueryRoleDetailResp
	QueryRoleListReq          = sysclient2.QueryRoleListReq
	QueryRoleListResp         = sysclient2.QueryRoleListResp
	QueryRoleMenuListReq      = sysclient2.QueryRoleMenuListReq
	QueryRoleMenuListResp     = sysclient2.QueryRoleMenuListResp
	QueryRoleUserListReq      = sysclient2.QueryRoleUserListReq
	QueryRoleUserListResp     = sysclient2.QueryRoleUserListResp
	QueryUserDetailReq        = sysclient2.QueryUserDetailReq
	QueryUserDetailResp       = sysclient2.QueryUserDetailResp
	QueryUserListReq          = sysclient2.QueryUserListReq
	QueryUserListResp         = sysclient2.QueryUserListResp
	QueryUserRoleListReq      = sysclient2.QueryUserRoleListReq
	QueryUserRoleListResp     = sysclient2.QueryUserRoleListResp
	ReSetPasswordReq          = sysclient2.ReSetPasswordReq
	ReSetPasswordResp         = sysclient2.ReSetPasswordResp
	RoleData                  = sysclient2.RoleData
	RoleListData              = sysclient2.RoleListData
	UpdateDeptReq             = sysclient2.UpdateDeptReq
	UpdateDeptResp            = sysclient2.UpdateDeptResp
	UpdateDeptStatusReq       = sysclient2.UpdateDeptStatusReq
	UpdateDeptStatusResp      = sysclient2.UpdateDeptStatusResp
	UpdateDictItemReq         = sysclient2.UpdateDictItemReq
	UpdateDictItemResp        = sysclient2.UpdateDictItemResp
	UpdateDictItemStatusReq   = sysclient2.UpdateDictItemStatusReq
	UpdateDictItemStatusResp  = sysclient2.UpdateDictItemStatusResp
	UpdateDictTypeReq         = sysclient2.UpdateDictTypeReq
	UpdateDictTypeResp        = sysclient2.UpdateDictTypeResp
	UpdateDictTypeStatusReq   = sysclient2.UpdateDictTypeStatusReq
	UpdateDictTypeStatusResp  = sysclient2.UpdateDictTypeStatusResp
	UpdateMenuReq             = sysclient2.UpdateMenuReq
	UpdateMenuResp            = sysclient2.UpdateMenuResp
	UpdateMenuRoleReq         = sysclient2.UpdateMenuRoleReq
	UpdateMenuRoleResp        = sysclient2.UpdateMenuRoleResp
	UpdateMenuStatusReq       = sysclient2.UpdateMenuStatusReq
	UpdateMenuStatusResp      = sysclient2.UpdateMenuStatusResp
	UpdatePostReq             = sysclient2.UpdatePostReq
	UpdatePostResp            = sysclient2.UpdatePostResp
	UpdatePostStatusReq       = sysclient2.UpdatePostStatusReq
	UpdatePostStatusResp      = sysclient2.UpdatePostStatusResp
	UpdateRoleReq             = sysclient2.UpdateRoleReq
	UpdateRoleResp            = sysclient2.UpdateRoleResp
	UpdateRoleStatusReq       = sysclient2.UpdateRoleStatusReq
	UpdateRoleStatusResp      = sysclient2.UpdateRoleStatusResp
	UpdateUserReq             = sysclient2.UpdateUserReq
	UpdateUserResp            = sysclient2.UpdateUserResp
	UpdateUserRoleListReq     = sysclient2.UpdateUserRoleListReq
	UpdateUserRoleListResp    = sysclient2.UpdateUserRoleListResp
	UpdateUserStatusReq       = sysclient2.UpdateUserStatusReq
	UpdateUserStatusResp      = sysclient2.UpdateUserStatusResp
	UserData                  = sysclient2.UserData
	UserListData              = sysclient2.UserListData

	UserService interface {
		// 用户登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 获取用户个人信息
		UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
		// 重置用户密码
		ReSetPassword(ctx context.Context, in *ReSetPasswordReq, opts ...grpc.CallOption) (*ReSetPasswordResp, error)
		// 添加用户信息表
		AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error)
		// 删除用户信息表
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
		// 更新用户信息表
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error)
		// 更新用户信息表状态
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*UpdateUserStatusResp, error)
		// 查询用户信息表详情
		QueryUserDetail(ctx context.Context, in *QueryUserDetailReq, opts ...grpc.CallOption) (*QueryUserDetailResp, error)
		// 查询用户信息表列表
		QueryUserList(ctx context.Context, in *QueryUserListReq, opts ...grpc.CallOption) (*QueryUserListResp, error)
		// 查询用户与角色的关联
		QueryUserRoleList(ctx context.Context, in *QueryUserRoleListReq, opts ...grpc.CallOption) (*QueryUserRoleListResp, error)
		// 更新用户与角色的关联
		UpdateUserRoleList(ctx context.Context, in *UpdateUserRoleListReq, opts ...grpc.CallOption) (*UpdateUserRoleListResp, error)
		// 查询所有部门和岗位
		QueryDeptAndPostList(ctx context.Context, in *QueryDeptAndPostListReq, opts ...grpc.CallOption) (*QueryDeptAndPostListResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 用户登录
func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户个人信息
func (m *defaultUserService) UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

// 重置用户密码
func (m *defaultUserService) ReSetPassword(ctx context.Context, in *ReSetPasswordReq, opts ...grpc.CallOption) (*ReSetPasswordResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.ReSetPassword(ctx, in, opts...)
}

// 添加用户信息表
func (m *defaultUserService) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.AddUser(ctx, in, opts...)
}

// 删除用户信息表
func (m *defaultUserService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

// 更新用户信息表
func (m *defaultUserService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

// 更新用户信息表状态
func (m *defaultUserService) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*UpdateUserStatusResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

// 查询用户信息表详情
func (m *defaultUserService) QueryUserDetail(ctx context.Context, in *QueryUserDetailReq, opts ...grpc.CallOption) (*QueryUserDetailResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.QueryUserDetail(ctx, in, opts...)
}

// 查询用户信息表列表
func (m *defaultUserService) QueryUserList(ctx context.Context, in *QueryUserListReq, opts ...grpc.CallOption) (*QueryUserListResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.QueryUserList(ctx, in, opts...)
}

// 查询用户与角色的关联
func (m *defaultUserService) QueryUserRoleList(ctx context.Context, in *QueryUserRoleListReq, opts ...grpc.CallOption) (*QueryUserRoleListResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.QueryUserRoleList(ctx, in, opts...)
}

// 更新用户与角色的关联
func (m *defaultUserService) UpdateUserRoleList(ctx context.Context, in *UpdateUserRoleListReq, opts ...grpc.CallOption) (*UpdateUserRoleListResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserRoleList(ctx, in, opts...)
}

// 查询所有部门和岗位
func (m *defaultUserService) QueryDeptAndPostList(ctx context.Context, in *QueryDeptAndPostListReq, opts ...grpc.CallOption) (*QueryDeptAndPostListResp, error) {
	client := sysclient2.NewUserServiceClient(m.cli.Conn())
	return client.QueryDeptAndPostList(ctx, in, opts...)
}
