// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"
	"github.com/summer-gonner/traffica/sys/internal/logic/loginlogservice"
	"github.com/summer-gonner/traffica/sys/internal/svc"
	sysclient2 "github.com/summer-gonner/traffica/sys/sysclient"
)

type LoginLogServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient2.UnimplementedLoginLogServiceServer
}

func NewLoginLogServiceServer(svcCtx *svc.ServiceContext) *LoginLogServiceServer {
	return &LoginLogServiceServer{
		svcCtx: svcCtx,
	}
}

// 删除系统登录日志表
func (s *LoginLogServiceServer) DeleteLoginLog(ctx context.Context, in *sysclient2.DeleteLoginLogReq) (*sysclient2.DeleteLoginLogResp, error) {
	l := loginlogservicelogic.NewDeleteLoginLogLogic(ctx, s.svcCtx)
	return l.DeleteLoginLog(in)
}

// 查询系统登录日志表详情
func (s *LoginLogServiceServer) QueryLoginLogDetail(ctx context.Context, in *sysclient2.QueryLoginLogDetailReq) (*sysclient2.QueryLoginLogDetailResp, error) {
	l := loginlogservicelogic.NewQueryLoginLogDetailLogic(ctx, s.svcCtx)
	return l.QueryLoginLogDetail(in)
}

// 查询系统登录日志表列表
func (s *LoginLogServiceServer) QueryLoginLogList(ctx context.Context, in *sysclient2.QueryLoginLogListReq) (*sysclient2.QueryLoginLogListResp, error) {
	l := loginlogservicelogic.NewQueryLoginLogListLogic(ctx, s.svcCtx)
	return l.QueryLoginLogList(in)
}
