// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"
	"github.com/summmer-gonner/traffica/sys/internal/logic/dicttypeservice"
	"github.com/summmer-gonner/traffica/sys/internal/svc"
	sysclient2 "github.com/summmer-gonner/traffica/sys/sysclient"
)

type DictTypeServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient2.UnimplementedDictTypeServiceServer
}

func NewDictTypeServiceServer(svcCtx *svc.ServiceContext) *DictTypeServiceServer {
	return &DictTypeServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加字典类型表
func (s *DictTypeServiceServer) AddDictType(ctx context.Context, in *sysclient2.AddDictTypeReq) (*sysclient2.AddDictTypeResp, error) {
	l := dicttypeservicelogic.NewAddDictTypeLogic(ctx, s.svcCtx)
	return l.AddDictType(in)
}

// 删除字典类型表
func (s *DictTypeServiceServer) DeleteDictType(ctx context.Context, in *sysclient2.DeleteDictTypeReq) (*sysclient2.DeleteDictTypeResp, error) {
	l := dicttypeservicelogic.NewDeleteDictTypeLogic(ctx, s.svcCtx)
	return l.DeleteDictType(in)
}

// 更新字典类型表
func (s *DictTypeServiceServer) UpdateDictType(ctx context.Context, in *sysclient2.UpdateDictTypeReq) (*sysclient2.UpdateDictTypeResp, error) {
	l := dicttypeservicelogic.NewUpdateDictTypeLogic(ctx, s.svcCtx)
	return l.UpdateDictType(in)
}

// 更新字典类型表状态
func (s *DictTypeServiceServer) UpdateDictTypeStatus(ctx context.Context, in *sysclient2.UpdateDictTypeStatusReq) (*sysclient2.UpdateDictTypeStatusResp, error) {
	l := dicttypeservicelogic.NewUpdateDictTypeStatusLogic(ctx, s.svcCtx)
	return l.UpdateDictTypeStatus(in)
}

// 查询字典类型表详情
func (s *DictTypeServiceServer) QueryDictTypeDetail(ctx context.Context, in *sysclient2.QueryDictTypeDetailReq) (*sysclient2.QueryDictTypeDetailResp, error) {
	l := dicttypeservicelogic.dicttypeservicelogic.NewQueryDictTypeDetailLogic(ctx, s.svcCtx)
	return l.QueryDictTypeDetail(in)
}

// 查询字典类型表列表
func (s *DictTypeServiceServer) QueryDictTypeList(ctx context.Context, in *sysclient2.QueryDictTypeListReq) (*sysclient2.QueryDictTypeListResp, error) {
	l := dicttypeservicelogic.NewQueryDictTypeListLogic(ctx, s.svcCtx)
	return l.QueryDictTypeList(in)
}
